### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by mahafeeling** [ZJU-FAST-Lab/Terrestrial-Aerial-Navigation#1]
您好，我在ubuntu18.04，RTX3060，cuda11.04下进行编译catkin_make后报错nvcc fatal   : Unsupported gpu architecture 'compute_86'，我在英伟达官网查询了算力为8.6，环境配置也没有问题，请问报错的原因是什么呢？

**Comment by avicomac** [comment]
你好，我也遇到这个问题了，rtx3060，请问你解决了吗

**Comment by RoboticsZhang** [comment]
Sorry for late reply, maybe you need to update the graphics card driver or CUDA.

**Comment by RoboticsZhang** [comment]
Sorry for late reply, maybe you need to update the graphics card driver or CUDA.
