### ISSUE TITLE
不使用cuda，在rviz中不能建立local_map

### ISSUE THREAD

**Issue by mahafeeling** [ZJU-FAST-Lab/Terrestrial-Aerial-Navigation#2]
由于cuda问题，我在CMakeLists.txt中设置set(ENABLE_CUDA false)，通过编译后运行launch文件，发现并没有显示绿色的局部感知地图，请问是什么原因导致的呢？

![2023-05-24 00-01-17 的屏幕截图](https://github.com/ZJU-FAST-Lab/Terrestrial-Aerial-Navigation/assets/38601636/f1a3e523-2e64-47d9-a615-d70e8ec8c337)

**Comment by mahafeeling** [comment]
已经解决，主要问题是在local_sencing的CMakeLists.txt中没有写不使用cuda时的编译要求，因此不使用cuda就无法实现局部感知。

**Comment by Chai8226** [comment]
你好，我想问问你是怎么解决的呀，能分享一下你的local_sencing的CMakeLists.txt吗，万分感谢

**Comment by chenbochenbo1** [comment]
> 你好，我想问问你是怎么解决的呀，能分享一下你的local_sencing的CMakeLists.txt吗，万分感谢
你好，请问你解决了吗，我现在就是仿真跑起来了，但是整个运动都是直线，没有避障，也没局部地图感知
