### ISSUE TITLE
Why genetated the question of “”Make sure file exists in package path and permission is set to executable (chmod +x)"

### ISSUE THREAD

**Issue by LiuL0ngl0ng** [ZJU-FAST-Lab/Terrestrial-Aerial-Navigation#3]
ERROR: cannot launch node of type [poly_traj_server/poly_traj_server_node]: Cannot locate node of type [poly_traj_server_node] in package [poly_traj_server]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by yuxin-kang** [comment]
Hello, have you solved this problem? I also encountered this problem.

**Comment by White11B** [comment]
me too

**Comment by LiuL0ngl0ng** [comment]
> ERROR: cannot launch node of type [poly_traj_server/poly_traj_server_node]: Cannot locate node of type [poly_traj_server_node] in package [poly_traj_server]. Make sure file exists in package path and permission is set to executable (chmod +x)

You can modify  the 370 row "ros::init(argc, argv, "traj_server") " to ""ros::init(argc, argv, "poly_traj_server")"  in the cpp source file of src/uav_simulator/Utils/poly_traj_server/src/traj_server.cpp, but I haven't tried yet.

**Comment by RoboticsZhang** [comment]
Sorry for late reply, I have fixing the above bug, you can try to run this project again XD
